name: Auto Translate Issues and PRs

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]
  push:
    paths:
      - '**.md'  # Runs on markdown file changes

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Google Translate API client
        run: pip install google-cloud-translate requests

      - name: Translate content
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_TRANSLATE_API_KEY: ${{ secrets.GOOGLE_TRANSLATE_API_KEY }}
        run: |
          python .github/scripts/translate.py
